# Generated by Django 5.0.2 on 2024-02-27 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockApp", "0002_alter_customuser_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(unique=True)),
                ("name", models.CharField()),
                ("exchange", models.CharField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (0, "Closed-end Fund"),
                            (1, "Common Stock"),
                            (2, "Depositary Receipt"),
                            (3, "ETF"),
                            (4, "Exchange-Traded Note"),
                            (5, "Global Depositary Receipt"),
                            (6, "Limited Partnership"),
                            (7, "Mutual Fund"),
                            (8, "Preferred Stock"),
                            (9, "REIT"),
                            (10, "Right"),
                            (11, "Structured Product"),
                            (12, "Trust"),
                            (13, "Unit"),
                            (14, "Warrant"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stockApp.currency",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stockApp.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTimeSeriesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.FloatField()),
                ("date", models.DateField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stockApp.stockdata",
                    ),
                ),
            ],
        ),
    ]
