# Generated by Django 5.0.2 on 2024-02-27 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockApp", "0002_alter_customuser_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(unique=True)),
                ("name", models.CharField()),
                ("exchange", models.CharField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Closed-end Fund", "Closed End Fund"),
                            ("Common Stock", "Common Stock"),
                            ("Depositary Receipt", "Depositary Receipt"),
                            ("ETF", "Etf"),
                            ("Exchange-Traded Note", "Exchange Traded Note"),
                            ("Global Depositary Receipt", "Global Depositary Receipt"),
                            ("Limited Partnership", "Limited Partnership"),
                            ("Mutual Fund", "Mutual Fund"),
                            ("Preferred Stock", "Preferred Stock"),
                            ("REIT", "Reit"),
                            ("Right", "Right"),
                            ("Structured Product", "Structured Product"),
                            ("Trust", "Trust"),
                            ("Unit", "Unit"),
                            ("Warrant", "Warrant"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_time_series_update", models.DateField(default=None, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stockApp.country",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stockApp.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTimeSeriesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.FloatField()),
                ("date", models.DateField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stockApp.stockdata",
                    ),
                ),
            ],
        ),
    ]
