# Generated by Django 5.0.2 on 2024-03-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockApp", "0003_country_currency_stockdata_stocktimeseriesdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(to="stockApp.stockdata"),
        ),
    ]
